version: 0.2

env:
  parameter-store:
    SONAR_TOKEN: "/Givson/sonar-token"
    SONAR_URL: "/my-practice-app/sonar-url"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing SonarQube Scanner CLI..."
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip -q sonar-scanner-cli-4.7.0.2747-linux.zip
      - export PATH=$PATH:$PWD/sonar-scanner-4.7.0.2747-linux/bin

  build:
    commands:
      - echo "Building project and running Maven verify..."
      - mvn clean verify

      - echo "Executing SonarQube Analysis scan..."
      - sonar-scanner \
          -Dsonar.projectKey=my-practice-app \
          -Dsonar.sources=. \
          -Dsonar.host.url="$SONAR_URL" \
          -Dsonar.login="$SONAR_TOKEN"
